# Generated by Django 4.2.9 on 2024-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="registration_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=122)),
                ("lname", models.CharField(max_length=122)),
                ("email", models.EmailField(max_length=30)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.IntegerField(max_length=10)),
            ],
        ),
    ]
