# Generated by Django 4.2.9 on 2024-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="login_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
